# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 577)
        self.info = QtWidgets.QPushButton(Dialog)
        self.info.setGeometry(QtCore.QRect(490, 110, 101, 23))
        self.info.setObjectName("info")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(47, 530, 581, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.updates = QtWidgets.QLabel(Dialog)
        self.updates.setGeometry(QtCore.QRect(300, 480, 181, 20))
        self.updates.setObjectName("updates")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 47, 13))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(50, 40, 541, 61))
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.url = QtWidgets.QLabel(self.widget)
        self.url.setObjectName("url")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.url)
        self.urlinput = QtWidgets.QLineEdit(self.widget)
        self.urlinput.setObjectName("urlinput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urlinput)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(50, 160, 541, 194))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.title = QtWidgets.QLabel(self.widget1)
        self.title.setObjectName("title")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.title)
        self.titleinput = QtWidgets.QLineEdit(self.widget1)
        self.titleinput.setObjectName("titleinput")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleinput)
        self.author = QtWidgets.QLabel(self.widget1)
        self.author.setObjectName("author")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.author)
        self.authorinput = QtWidgets.QLineEdit(self.widget1)
        self.authorinput.setObjectName("authorinput")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.authorinput)
        self.rating = QtWidgets.QLabel(self.widget1)
        self.rating.setObjectName("rating")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rating)
        self.ratinginput = QtWidgets.QLineEdit(self.widget1)
        self.ratinginput.setObjectName("ratinginput")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ratinginput)
        self.views = QtWidgets.QLabel(self.widget1)
        self.views.setObjectName("views")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.views)
        self.viewsinput = QtWidgets.QLineEdit(self.widget1)
        self.viewsinput.setObjectName("viewsinput")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.viewsinput)
        self.length = QtWidgets.QLabel(self.widget1)
        self.length.setObjectName("length")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.length)
        self.lengthinput = QtWidgets.QLineEdit(self.widget1)
        self.lengthinput.setObjectName("lengthinput")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lengthinput)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.graphicsView = QtWidgets.QGraphicsView(self.widget1)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(50, 380, 181, 101))
        self.widget2.setObjectName("widget2")
        self.formLayout = QtWidgets.QFormLayout(self.widget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.type = QtWidgets.QLabel(self.widget2)
        self.type.setObjectName("type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.type)
        self.typeinput = QtWidgets.QComboBox(self.widget2)
        self.typeinput.setObjectName("typeinput")
        self.typeinput.addItem("")
        self.typeinput.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.typeinput)
        self.resolution = QtWidgets.QLabel(self.widget2)
        self.resolution.setObjectName("resolution")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.resolution)
        self.resolutioninput = QtWidgets.QComboBox(self.widget2)
        self.resolutioninput.setObjectName("resolutioninput")
        self.resolutioninput.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.resolutioninput)
        self.abr = QtWidgets.QLabel(self.widget2)
        self.abr.setObjectName("abr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.abr)
        self.abrinput = QtWidgets.QComboBox(self.widget2)
        self.abrinput.setObjectName("abrinput")
        self.abrinput.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.abrinput)
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(420, 410, 171, 31))
        self.widget3.setObjectName("widget3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.cancel = QtWidgets.QPushButton(self.widget3)
        self.cancel.setObjectName("cancel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cancel)
        self.download = QtWidgets.QPushButton(self.widget3)
        self.download.setObjectName("download")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.download)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Yt Downloader"))
        self.info.setText(_translate("Dialog", "Info"))
        self.updates.setText(_translate("Dialog", ""))
        self.label.setText(_translate("Dialog", "Enter URL"))
        self.url.setText(_translate("Dialog", "URL"))
        self.title.setText(_translate("Dialog", "Title"))
        self.author.setText(_translate("Dialog", "Author"))
        self.rating.setText(_translate("Dialog", "Ratings"))
        self.views.setText(_translate("Dialog", "Views"))
        self.length.setText(_translate("Dialog", "Length"))
        self.type.setText(_translate("Dialog", "Type"))
        self.typeinput.setItemText(0, _translate("Dialog", "Audio"))
        self.typeinput.setItemText(1, _translate("Dialog", "Video"))
        self.resolution.setText(_translate("Dialog", "Resolution"))
        self.resolutioninput.setItemText(0, _translate("Dialog", ""))
        self.abr.setText(_translate("Dialog", "ABR"))
        self.abrinput.setItemText(0, _translate("Dialog", ""))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.download.setText(_translate("Dialog", "Download"))

